# ----------------------------------------------------------------------------------------------------
# Pipeline used by the azd command
# ----------------------------------------------------------------------------------------------------
name: python.function.demo

infra:
    provider: bicep
    path: infra
    module: main

pipeline:
    provider: github

services:
  function:
    project: src/FunctionApp/
    language: python
    host: function
