# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and Function App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.infra.and.function
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 
      
jobs:
# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build Artifacts
    uses: ./.github/workflows/template-function-app-build.yml
    with:
      envCode: 'dev'
      rootDirectory: 'src/FunctionApp'
    secrets: inherit

# ------------------------------------------------------------------------------------------------------------------------
  infra-dev:
    name: Create Dev Infra
    needs: build-app
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'demo'
      location: 'eastus'
      storageSku: 'Standard_LRS'
      functionName: 'process'
      functionAppSku: 'Y1'
      functionAppSkuFamily: 'Y'
      functionAppSkuTier: 'Dynamic'

  deploy-dev:
    name: Deploy Dev App
    needs: infra-dev
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'dev'
      functionName: 'process'

# ------------------------------------------------------------------------------------------------------------------------
  infra-qa:
    name: Create QA Infra
    needs: deploy-dev
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'qa'
      location: 'eastus'
      storageSku: 'Standard_LRS'
      functionName: 'process'
      functionAppSku: 'Y1'
      functionAppSkuFamily: 'Y'
      functionAppSkuTier: 'Dynamic'

  deploy-qa:
    name: Deploy QA App
    needs: infra-qa
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'qa'
      functionName: 'process'
