# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.infra
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  infra-dev:
    name: Create Dev Infra
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'dev'
      location: 'eastus'
      storageSku: 'Standard_LRS'
      functionName: 'process'
      functionAppSku: 'Y1'
      functionAppSkuFamily: 'Y'
      functionAppSkuTier: 'Dynamic'

  infra-qa:
    name: Create QA Infra
    needs: infra-dev
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'qa'
      location: 'eastus'
      storageSku: 'Standard_LRS'
      functionName: 'process'
      functionAppSku: 'Y1'
      functionAppSkuFamily: 'Y'
      functionAppSkuTier: 'Dynamic'
