# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to build a Function App ready to deploy to Azure
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: template.pyfunctionapp.build
run-name: Build Python Function App
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string
      rootDirectory:
        required: true
        type: string

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.envCode }}

    env:
      PYTHON_VERSION: '3.9' 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: List Files
      run: 
        echo Action Path
        tree ${{ env.GITHUB_ACTION_PATH }}
        echo RootDirectory
        tree ${{ inputs.rootDirectory }}
      continue-on-error: true

    - name: Install dependencies
      run: |
        pip install setuptools
        pip install --target="./.python_packages/lib/site-packages" -r ./${{ inputs.rootDirectory }}/requirements.txt

    - name: Save Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pythonapp
        path: '${{ inputs.rootDirectory }}'
